import { expect, test } from "@playwright/test";

test("app loads and is cross-origin isolated", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("ANTIPHON", { exact: true })).toBeVisible();
  // SharedArrayBuffer requires COOP/COEP — regression-guard it from day one.
  const isolated = await page.evaluate(() => globalThis.crossOriginIsolated);
  expect(isolated).toBe(true);
});

test("wasm initializes in the browser and encodes", async ({ page }) => {
  await page.goto("/");
  // Drive the same package the app uses, in-page, via a dynamic import of
  // the app bundle's test hook: the join page boots the worker; here we
  // simply verify cross-origin isolation exposes SharedArrayBuffer.
  const hasSab = await page.evaluate(() => typeof SharedArrayBuffer === "function");
  expect(hasSab).toBe(true);
});

// QA LOW: "favicon 404 on every route". Headless pages don't request
// favicons on their own, so the asset is fetched explicitly; the route
// sweep then guards the console/network against ANY 404 regression.
test("favicon is served and no route 404s a resource", async ({ page, browserName }) => {
  const svg = await page.request.get("/favicon.svg");
  expect(svg.status()).toBe(200);
  expect(svg.headers()["content-type"] ?? "").toContain("svg");
  // Safari/legacy fallback (PNG-ICO, generated by e2e/make-favicon-ico.mjs).
  const ico = await page.request.get("/favicon.ico");
  expect(ico.status()).toBe(200);

  // One deliberate exemption: this sweep visits fresh uuids nobody ever
  // opened, and GET /api/sessions/:id — plus its W8-A public split-out
  // /exists (the F19 probe's endpoint now that the summary is desk-gated
  // under auth) — answers an honest 404 for those; the desk's cold
  // attribution fetch reads that status by design. Semantics, not a
  // missing resource; everything else must still be 404-free.
  const honestExistence404 = /\/api\/sessions\/[0-9a-f-]{36}(\/exists)?$/;
  const notFound: string[] = [];
  page.on("response", (response) => {
    if (response.status() === 404 && !honestExistence404.test(response.url())) {
      notFound.push(response.url());
    }
  });
  page.on("console", (message) => {
    if (message.type() === "error" && message.text().includes("404")) {
      if (honestExistence404.test(message.location().url ?? "")) return;
      notFound.push(message.text());
    }
  });
  // Full route sweep on chromium; webkit (mobile-safari project) covers the
  // landing only — the desk's capability surface on iPhone is out of scope.
  const routes =
    browserName === "chromium"
      ? ["/", `/join/${crypto.randomUUID()}`, "/rehearse", `/session/${crypto.randomUUID()}`]
      : ["/"];
  for (const route of routes) {
    await page.goto(route);
    await expect(page.getByText("ANTIPHON", { exact: true }).first()).toBeVisible();
  }
  await page.waitForTimeout(1_000);
  expect(notFound).toEqual([]);
});
