//! Thin wasm-bindgen facade over `antiphon-core`/`-codec`.
//!
//! Built by wasm-pack into `packages/core-wasm` — the ONLY way TS consumes
//! Rust, in both the browser (encoder worker, desk sink worker) and Node
//! (server ingest). Glue only: every protocol decision lives in the inner
//! crates. Timestamps cross the boundary as f64 microseconds (exact far
//! beyond any session length); UUIDs as 16-byte arrays; frames as bytes.

mod drift;
mod json;
mod recorder;
mod sink;

pub use drift::DriftEstimator;
pub use recorder::RecorderEngine;
pub use sink::{IngestResult, SinkEngine, TimeSyncSession};

use wasm_bindgen::prelude::*;

/// Smoke-test export proving the wasm pipeline works end to end.
#[wasm_bindgen]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Calibration chirp samples (RFC §10): exponential sine sweep, generated by
/// the same Rust that will correlate against it. TS only plays it.
#[wasm_bindgen]
pub fn generate_chirp(
    sample_rate: u32,
    start_hz: f32,
    end_hz: f32,
    duration_ms: f32,
    gain_dbfs: f32,
) -> Vec<f32> {
    antiphon_dsp::chirp::generate_ess(sample_rate, start_hz, end_hz, duration_ms, gain_dbfs)
}

/// Locate the calibration chirp in captured PCM. Returns JSON
/// `{"lagSamples":n,"peak":x,"confidence":y}` or `null` when nothing
/// resembling the sweep is present. `repeats`/`gap_ms` describe the §10
/// emission schedule so the sibling sweep isn't scored as a sidelobe. The
/// chirp position per stream maps every sample domain onto the shared room
/// clock (RFC §10).
#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn find_chirp_offset(
    signal: &[f32],
    sample_rate: u32,
    start_hz: f32,
    end_hz: f32,
    duration_ms: f32,
    gain_dbfs: f32,
    repeats: u32,
    gap_ms: f32,
) -> Option<String> {
    antiphon_dsp::correlate::find_chirp(
        signal,
        sample_rate,
        start_hz,
        end_hz,
        duration_ms,
        gain_dbfs,
        repeats,
        gap_ms,
    )
    .map(|m| {
        format!(
            "{{\"lagSamples\":{},\"peak\":{},\"confidence\":{}}}",
            m.lag_samples,
            if m.peak.is_finite() { m.peak } else { 0.0 },
            if m.confidence.is_finite() {
                m.confidence
            } else {
                1.0e9
            },
        )
    })
}

/// Content-based stream alignment (W4-B): locate `target`'s recorded
/// content inside `reference` — the chirp-less fallback. Returns JSON
/// `{"lagSamples":n,"peak":x,"confidence":y}` (lagSamples SIGNED: the
/// target's extra pre-roll relative to the reference — same trim-more
/// semantics as a chirp lag difference) or `null` when the streams share
/// no locatable content (silence, uncorrelated takes, non-finite input).
/// Callers pass stream HEADS only (the algorithm caps at 60 s anyway);
/// full 45-min streams must never cross this boundary.
#[wasm_bindgen]
pub fn align_content(reference: &[f32], target: &[f32], sample_rate: u32) -> Option<String> {
    antiphon_dsp::content::align_content(reference, target, sample_rate).map(|m| {
        format!(
            "{{\"lagSamples\":{},\"peak\":{},\"confidence\":{}}}",
            m.lag_samples,
            if m.peak.is_finite() { m.peak } else { 0.0 },
            // The dsp side bounds confidence (MAX_PROMINENCE × consensus);
            // a non-finite value here would be a bug, so it degrades to 0
            // — an impossible-to-accept verdict, never a free pass.
            if m.confidence.is_finite() {
                m.confidence
            } else {
                0.0
            },
        )
    })
}

/// One-shot mono FLAC encode for desk stem exports (W5-C): Web-Audio
/// floats in, a complete decodable `.flac` file out — the same encoder the
/// phones capture through (packages/codec), with STREAMINFO finalized
/// (total samples are known up front, unlike the streaming path). Call
/// from the desk main thread with one rendered stem buffer at a time.
#[wasm_bindgen]
pub fn encode_flac_mono(
    samples: &[f32],
    sample_rate: u32,
    bits_per_sample: u8,
) -> Result<Vec<u8>, JsError> {
    antiphon_codec::encode_flac_mono(
        antiphon_codec::EncoderConfig {
            sample_rate,
            bits_per_sample,
        },
        samples,
    )
    .map_err(|e| JsError::new(&e.to_string()))
}

/// Protocol constants exposed for TS consumers (§13).
#[wasm_bindgen]
pub fn constants_json() -> String {
    format!(
        concat!(
            "{{\"maxFrameBytes\":{},\"nominalChunkMs\":{},\"minChunkMs\":{},",
            "\"ackIntervalMs\":{},\"ringMinSeconds\":{},\"timeSyncIntervalMs\":{},",
            "\"channelLabelData\":\"{}\",\"channelLabelSync\":\"{}\"}}"
        ),
        antiphon_core::constants::MAX_FRAME_BYTES,
        antiphon_core::constants::NOMINAL_CHUNK_MS,
        antiphon_core::constants::MIN_CHUNK_MS,
        antiphon_core::constants::ACK_INTERVAL_MS,
        antiphon_core::constants::RING_MIN_SECONDS,
        antiphon_core::constants::TIME_SYNC_INTERVAL_MS,
        antiphon_core::constants::CHANNEL_LABEL_DATA,
        antiphon_core::constants::CHANNEL_LABEL_SYNC,
    )
}

fn parse_id(bytes: &[u8], what: &str) -> Result<[u8; 16], JsError> {
    bytes
        .try_into()
        .map_err(|_| JsError::new(&format!("{what} must be exactly 16 bytes")))
}

/// Experimental METER frame type — from the private/experimental range the
/// RFC reserves (§6.1, 0x80–0xFF). Carries a recorder's instantaneous peak
/// level for live desk metering. Fire-and-forget UI telemetry: never
/// persisted, never acked, and any conformant receiver that doesn't know it
/// MUST ignore it. Not part of the normative protocol.
pub const FT_METER_EXPERIMENTAL: u8 = 0x80;
const METER_FRAME_LEN: usize = 4 + 16 + 16 + 4;

/// Build a METER frame: header ++ take_id ++ stream_id ++ peak (f32 LE).
#[wasm_bindgen]
pub fn encode_meter_frame(take_id: &[u8], stream_id: &[u8], peak: f32) -> Result<Vec<u8>, JsError> {
    let take = parse_id(take_id, "take_id")?;
    let stream = parse_id(stream_id, "stream_id")?;
    let mut out = Vec::with_capacity(METER_FRAME_LEN);
    out.extend_from_slice(&antiphon_core::constants::MAGIC);
    out.push(antiphon_core::constants::PROTOCOL_VERSION);
    out.push(FT_METER_EXPERIMENTAL);
    out.extend_from_slice(&take);
    out.extend_from_slice(&stream);
    out.extend_from_slice(&peak.clamp(0.0, 1.0).to_le_bytes());
    Ok(out)
}

/// Parse a METER frame → JSON `{takeId, streamId, peak}`, or null for
/// anything that isn't one.
#[wasm_bindgen]
pub fn decode_meter_frame(bytes: &[u8]) -> Option<String> {
    if bytes.len() != METER_FRAME_LEN
        || bytes[0..2] != antiphon_core::constants::MAGIC
        || bytes[2] != antiphon_core::constants::PROTOCOL_VERSION
        || bytes[3] != FT_METER_EXPERIMENTAL
    {
        return None;
    }
    let take_id: [u8; 16] = bytes[4..20].try_into().ok()?;
    let stream_id: [u8; 16] = bytes[20..36].try_into().ok()?;
    let peak = f32::from_le_bytes(bytes[36..40].try_into().ok()?);
    Some(
        crate::json::Obj::new()
            .str("takeId", crate::json::uuid_string(&take_id))
            .str("streamId", crate::json::uuid_string(&stream_id))
            .num(
                "peak",
                if peak.is_finite() {
                    peak.clamp(0.0, 1.0)
                } else {
                    0.0
                },
            )
            .build(),
    )
}
